version: "3.6"

services:
  cogvlm-agent:
    image: python:3.10.13-slim
    restart: unless-stopped
    working_dir: /app
    container_name: cogvlm-agent-chat-api
    networks:
        - glm3
    deploy:
        resources:
            reservations:
                devices:
                    - driver: nvidia
                      count: 1
                      capabilities: [gpu]
    environment:
      - MODEL_PATH=/home/ubuntu/llm_models/cogagent-chat
      - TOKENIZER_PATH=/home/ubuntu/llm_models/vicuna-7b-v1.5
      - TZ=Asia/Shanghai
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DOCKER=True
    ports:
      - 55003:8000
    volumes:
      - ./:/app
      - /home/ubuntu/llm_models/cogagent-chat:/home/ubuntu/llm_models/cogagent-chat
      - /home/ubuntu/llm_models/vicuna-7b-v1.5:/home/ubuntu/llm_models/vicuna-7b-v1.5
    command:
      - sh
      - -c
      - |
        sed -i s/deb.debian.org/mirrors.tencentyun.com/g /etc/apt/sources.list
        sed -i s/security.debian.org/mirrors.tencentyun.com/g /etc/apt/sources.list
        apt-get update
        python -m pip install -i  https://mirror.sjtu.edu.cn/pypi/web/simple --upgrade pip
        pip install -r requirements.txt -i  https://mirror.sjtu.edu.cn/pypi/web/simple
        python ./openai_demo/openai_api.py --bf16
      
networks:
    glm3:
          driver: bridge